default_language_version:
  python: python3

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # safety
      # - id: detect-private-key

      # compulsory file formats
      # - id: check-executables-have-shebangs
      # - id: check-shebang-scripts-are-executable

      # - id: check-yaml
      - id: check-json
      - id: check-toml

      # formatting conventions
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: name-tests-test
        args: [--pytest-test-first]

      # other
      # - id: check-merge-conflict
      # - id: no-commit-to-branch
      #  args: [--branch, main]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.6
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
exclude: '{{ cookiecutter.project_name }}/.*'

# by default, pre-commit only installs the pre-commit hook ("commit" stage),
# but you can tell `pre-commit install` to install other hooks
default_stages:
  - pre-commit
  - pre-merge-commit
  - manual
