[project]
name = "md_project_cookiecutter"
version = "0.1.0"
description = "Cookiecutter template for Molecular Dynamics and Computational Biology projects"
readme = "README.md"
requires-python = ">=3.10"
# license = { text = "MIT" }
authors = [
    { name = "Aleksandr Kovalenko", email = "ikovalenko239@gmail.com" }
]
keywords = ["cookiecutter", "template", "computational biology", "molecular simulation"]

dependencies = [
    "cookiecutter>=2.6.0",
]

[project.optional-dependencies]
lint = [
    "ruff",
    "mypy"
]
test = [
    "pytest-randomly",
    "pytest",
    "pytest-cov",
    "coverage-badge"
]
dev = [
    "md_project_cookiecutter[lint]",
    "md_project_cookiecutter[test]"
]

[project.urls]
homepage = "https://github.com/Aleksandr-biochem/md_project_cookiecutter"
issues = "https://github.com/Aleksandr-biochem/md_project_cookiecutter/issues"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.mypy]
# python_version = "3.10"
strict = true
ignore_missing_imports = true
files = ["hooks", "tests"]
